# Generated by Django 4.1.5 on 2023-01-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
 
    ]
