# Generated by Django 4.1.5 on 2023-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swiftcash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_acc', models.BigIntegerField()),
                ('to_acc', models.BigIntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('branch_code', models.IntegerField()),
                ('payee_name', models.CharField(max_length=50)),
                ('payee_acc', models.BigIntegerField()),
                ('cif', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('ph_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='Card_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
            options={
                'db_table': 'credit_card_his',
            },
        ),
        migrations.CreateModel(
            name='dth_payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pack', models.CharField(choices=[('for 1 month-RS 250.', 'for 1 month-RS 250.'), ('for 3 month-RS 650.', 'for 3 month-RS 650.'), ('for 6 month-RS 950.', 'for 6 month-RS 950.'), ('for 1 year-RS 1650.', 'for 1 year-RS 1650.')], max_length=97)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'dth',
            },
        ),
        migrations.CreateModel(
            name='EB_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('TamilNadu', 'TamilNadu'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('AndhraPradesh', 'AndhraPradesh')], max_length=17)),
                ('EB', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='h_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(choices=[('sbi', 'sbi'), ('iob', 'iob')], max_length=7)),
                ('bank_acc', models.BigIntegerField()),
                ('bank_ifsc', models.IntegerField()),
                ('acc_name', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'house_rent',
            },
        ),
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login_table',
            },
        ),
        migrations.CreateModel(
            name='Myform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('login_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('adhaar_num', models.BigIntegerField()),
                ('bank_acc', models.BigIntegerField()),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'signup',
            },
        ),
        migrations.CreateModel(
            name='recharge_payment_his',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pack', models.CharField(choices=[('549=UL Call 2GB/D,56D', '549=UL Call 2GB/D,56D'), ('65=4GB,existingpack', '65=4GB,existingpack.'), ('479=UL Call 1.5GB/D,56D.', '479=UL Call 1.5GB/D,56D.'), ('359=UL Call 2GB/D,28D.', '359=UL Call 2GB/D,28D.'), ('2999=UL Call 2GB/D,1Y', '2999=UL Call 2GB/D,1Y'), ('839=UL Call 2GB/D,84D', '839=UL Call 2GB/D,84D'), ('299=UL Call 2GB/D,28D', '299=UL Call 2GB/D,28D'), ('719=UL Call 1.5GB/D,84D', '719=UL Call 1.5GB/D,84D')], max_length=97)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'rec',
            },
        ),
        migrations.CreateModel(
            name='s_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(choices=[('sbi', 'sbi'), ('iob', 'iob')], max_length=7)),
                ('bank_acc', models.BigIntegerField()),
                ('bank_ifsc', models.IntegerField()),
                ('acc_name', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'social_maintenance',
            },
        ),
        migrations.CreateModel(
            name='s_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(choices=[('sbi', 'sbi'), ('iob', 'iob')], max_length=7)),
                ('bank_acc', models.BigIntegerField()),
                ('bank_ifsc', models.IntegerField()),
                ('acc_name', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'shop_rent',
            },
        ),
        migrations.CreateModel(
            name='selfbank_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.BigIntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('branch_code', models.IntegerField()),
                ('payee_name', models.CharField(max_length=50)),
                ('payee_acc', models.BigIntegerField()),
                ('cif', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('ph_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'selfbank_his',
            },
        ),
    ]
